### ISSUE TITLE
Failed Java CI on ubuntu-latest: Unable to open DISPLAY

### ISSUE THREAD

**Issue by chenghuiyuan** [nus-tic4002-AY2122s2/forum#9]
Didn't face this issue when running on development machine (Windows 10). Updated `mainClassName` in `build.gradle` to 
```
application {
    mainClassName = "basic.Launcher"
}
```

In `MainWindow.fxml`: 
```
fx:controller="basic.MainWindow"
```

My ip repo: https://github.com/chenghuiyuan/ip/tree/branch-A-CI

```
./runtest.sh
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME_11.0.14_x64: /opt/hostedtoolcache/jdk+fx/11.0.14/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk+fx/11.0.14/x64
    JAVA_HOME_11_0_14_X64: /opt/hostedtoolcache/jdk+fx/11.0.14/x64
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:4[3](https://github.com/chenghuiyuan/ip/runs/5081545109?check_suite_focus=true#step:8:3))
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:181)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:179)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:[4](https://github.com/chenghuiyuan/ip/runs/5081545109?check_suite_focus=true#step:8:4)1)
	at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:146)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:291)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:6[5](https://github.com/chenghuiyuan/ip/runs/5081545109?check_suite_focus=true#step:8:5)9)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:410)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:3[6](https://github.com/chenghuiyuan/ip/runs/5081545109?check_suite_focus=true#step:8:6)4)
```

**Comment by damithc** [comment]
@chenghuiyuan you can continue with the rest, as CI is not important for the iP. 
Note that GitHub actions are run in Display-less machines, which means it cannot run a regular GUI. CI can only JUnit tests that don't involve a GUI. It is possible to run GUI in such environments using the headless mode but it's more complicated.

**Comment by chenghuiyuan** [comment]
Noted. Thanks!
